### PR TITLE
Create forum page

### PR DESCRIPTION
**Pull request by amazinigmech2418**

### CODE REVIEW

**Comment by Pufflegamerz** [comment]
Iframe to the old website, http://corescript.html-5.me/forums/

**Comment by redmangospros** [comment]
We Can  redrict. Can I Be admin on the fourm?

**Comment by Pufflegamerz** [comment]
Do you want to admin account or your own?

**Comment by redmangospros** [comment]
My Own with admin
Userbame: redmen_admin

**Pull request merged**
